openapi: 3.0.0
info:
  title: Auth Service API
  description: API for user authentication
  version: 1.0.0

paths:
  /api/auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: user@example.com
                password:
                  type: string
                  example: Password123
      responses:
        '201':
          description: User created successfully
        '400':
          description: Invalid input

  /api/auth/login:
    post:
      summary: Log in a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: user@example.com
                password:
                  type: string
                  example: Password123
      responses:
        '200':
          description: Login successful
        '401':
          description: Unauthorized
